### PR TITLE
796 format accepted mailers grad

### LINKED ISSUE #796: Update Grad School Auto Mailers
AC
The grad school was under the impression that emails were being automatically sent to students when their format reviews were rejected or accepted. They would like this to be the case, like it currently is for honors and sset.

Also they have language changes, some major and some minor, to just about all the autoreply emails. 

TECH NOTES
Currently the logic for this exists on `workflow_mailer.rb`, lines 14/25, in which calling format_review_rejected/accepted raises an Exception is raised unless the partner is sset or honors. Additionally, see `format_review_update_service` lines 28/34, which only call the mailer method if the partner is sset or honors.

We will need to update the tests on `workflow_mailer_spec.rb`

### PR DESCRIPTION
**Pull request by jlandiseigsti**
closes #796

Updates the text of the mailers, and changes the logic so that the grad school has format_approved and format_rejected emails. Also updates tests and correct some test holes that were there.

### CODE REVIEW

File: db/schema.rb [hunk 1]
```diff
@@ -301,6 +301,7 @@
     t.string "lionpath_semester"
     t.string "academic_program"
     t.string "degree_checkout_status"
+    t.datetime "author_release_warning_sent_at"
```
Comment (ajkiessl) [inline db/schema.rb:304]: Just to be safe, let's remove this.

File: spec/mailers/workflow_mailer_spec.rb [hunk 2]
```diff
@@ -96,13 +65,13 @@
...
       it "tells them that their format review has been accepted" do
-        expect(email.body).to match(/Your thesis format review has been approved!/i)
+        expect(email.body).to match(/has been approved/i)
       end
     end
 
-    context "when the current partner is neither 'sset' or 'honors'" do
-      it "raises an exception" do
-        skip 'not sset nor honors' if current_partner.sset? || current_partner.honors?
+    context "when the current partner does not send format_review emails" do
```
Comment (ajkiessl) [inline spec/mailers/workflow_mailer_spec.rb:72]: This will need the `milsch: true` tag to make it run in CI.

File: spec/mailers/workflow_mailer_spec.rb [hunk 3]
```diff
@@ -155,14 +101,13 @@
       end
 
       it "tells them that their format review has been rejected" do
-        expect(email.body).to match(/Your thesis format review has been rejected./i)
+        expect(email.body).to match(/has been rejected/i)
       end
     end
 
-    context "when the current partner is neither 'sset' nor 'honors'" do
+    context "when the current partner should not send" do
```
Comment (ajkiessl) [inline spec/mailers/workflow_mailer_spec.rb:108]: This will need the `milsch: true` tag aswell

**Review by ajkiessl — CHANGES_REQUESTED** [review]
Just a couple small things.  Otherwise this looks good.  Thanks!

**Review by ajkiessl — APPROVED** [review]
Lgtm!
