### PR TITLE
Custom Reports: add new fields + fix browser/CSV export discrepancies

### LINKED ISSUE #463: Custom Report updates
The following file shows what columns Grad School would like added:

https://pennstateoffice365.sharepoint.com/:x:/s/GES/EVU9FYoGlv5Ll2-iHofVS1wBb1C5QjdFYUU55mSbZeVbfw?e=4%3Ay8MrWc&at=9&CID=D6EAFBF9-B135-4CB2-BEC2-F9E2B5596132

Make the 'Status' column more admin readable.  It uses statuses that are displayed to authors.  It would make more sense to the admins if the statuses reflected the bucket headings on the admin side.

### PR DESCRIPTION
**Pull request by nicktiberi**
Fixes #463.

Screen Shot 2022-05-24 at 3 10 20 PM

### CODE REVIEW

File: app/models/concerns/admin_statuses.rb [hunk 1]
```diff
@@ -0,0 +1,97 @@
+# frozen_string_literal: true
```
Comment (ajkiessl) [inline app/models/concerns/admin_statuses.rb:1]: I hate to drop this on you after you wrote all this, but I did find some code we could potentially use instead:
https://github.com/psu-libraries/etda_workflow/blob/main/app/presenters/admin/submission_form_view.rb#L19-L35
The wording for these are a little different, but the admins should still recognize these.  Also, the `@session` param/variable in there can be removed.  Using the `SubmissionFormView` might seem a little out of place in the custom reports, but at least we wouldn't be adding more code.

I could go either way.  The `AdminStatuses` seems a bit cleaner to me, however it is extra code that could be done by the `SubmissionFormView`.

**Review by ajkiessl — CHANGES_REQUESTED** [review]
Other than my comments, this looks good.  I deployed this out to the dev server here: https://submit-etda-dev.libraries.psu.edu/admin/custom_report .

We should probably consider some way to get the datatables to scroll left to right, but that doesn't need to be done with this issue.  It stretches pretty far to the right.

**Review by ajkiessl — APPROVED** [review]
Looks good!  Thanks!
